apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a9fahm5mw-python 
  janus-idp.io/tekton: a9fahm5mw-python
  backstage.io/kubernetes-id: a9fahm5mw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9fahm5mw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml